dist: xenial
language: python

matrix:
    include:
        # Explicitly tell Travis which Python version to use for which
        # tox environment, instead of using one Python version in Travis and
        # hoping that tox and pyenv run the tests in the desired versions.
        # https://github.com/travis-ci/travis-ci/issues/8363#issuecomment-355090242
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38

install:
    - pip install -U tox
    - pip install -U coveralls

script:
    - tox

after_success:
    coveralls
